### ISSUE TITLE
Mod could not be loaded

### ISSUE THREAD

**Issue by Stakerpro** [Owyn/show_hp_etchings#1]
Mod was working fine yesterday and today i got a error message, not sure what is causing.

[00:27:32.983] [mods] ERROR: Module "Show HP etchings" (show_hp_etchings) could not be loaded!
[00:27:32.984] [mods] ERROR: Please contact the module's author: https://github.com/Owyn/show_hp_etchings/issues
[00:27:32.985] ReferenceError: dispatch is not defined
    at new show_hp_etchings (C:\Users\PC\AppData\Local\Programs\TeraToolbox\mods\show_hp_etchings-master\index.js:4:32)
    at ModuleManager.load (C:\Users\PC\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\PC\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\PC\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\PC\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1047:10)

**Comment by Owyn** [comment]
fixed

**Comment by Stakerpro** [comment]
Thank you very much.
